//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AppFacultativa.MovimientosCuenta {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MovimientoCuentaSoap", Namespace="http://tempuri.org/")]
    public partial class MovimientoCuenta : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetCuentaUSuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback DetalleCuentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback CuentaUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificarCuentaUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarCuentaUsuarioOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MovimientoCuenta() {
            this.Url = "https://localhost:44354/Servicios/MovimientoCuenta.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetCuentaUSuarioCompletedEventHandler GetCuentaUSuarioCompleted;
        
        /// <remarks/>
        public event DetalleCuentaCompletedEventHandler DetalleCuentaCompleted;
        
        /// <remarks/>
        public event CuentaUsuarioCompletedEventHandler CuentaUsuarioCompleted;
        
        /// <remarks/>
        public event ModificarCuentaUsuarioCompletedEventHandler ModificarCuentaUsuarioCompleted;
        
        /// <remarks/>
        public event EliminarCuentaUsuarioCompletedEventHandler EliminarCuentaUsuarioCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCuentaUSuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CuentaUsuario[] GetCuentaUSuario(int userID) {
            object[] results = this.Invoke("GetCuentaUSuario", new object[] {
                        userID});
            return ((CuentaUsuario[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCuentaUSuarioAsync(int userID) {
            this.GetCuentaUSuarioAsync(userID, null);
        }
        
        /// <remarks/>
        public void GetCuentaUSuarioAsync(int userID, object userState) {
            if ((this.GetCuentaUSuarioOperationCompleted == null)) {
                this.GetCuentaUSuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCuentaUSuarioOperationCompleted);
            }
            this.InvokeAsync("GetCuentaUSuario", new object[] {
                        userID}, this.GetCuentaUSuarioOperationCompleted, userState);
        }
        
        private void OnGetCuentaUSuarioOperationCompleted(object arg) {
            if ((this.GetCuentaUSuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCuentaUSuarioCompleted(this, new GetCuentaUSuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DetalleCuenta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CuentaUsuario DetalleCuenta([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> id) {
            object[] results = this.Invoke("DetalleCuenta", new object[] {
                        id});
            return ((CuentaUsuario)(results[0]));
        }
        
        /// <remarks/>
        public void DetalleCuentaAsync(System.Nullable<int> id) {
            this.DetalleCuentaAsync(id, null);
        }
        
        /// <remarks/>
        public void DetalleCuentaAsync(System.Nullable<int> id, object userState) {
            if ((this.DetalleCuentaOperationCompleted == null)) {
                this.DetalleCuentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDetalleCuentaOperationCompleted);
            }
            this.InvokeAsync("DetalleCuenta", new object[] {
                        id}, this.DetalleCuentaOperationCompleted, userState);
        }
        
        private void OnDetalleCuentaOperationCompleted(object arg) {
            if ((this.DetalleCuentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DetalleCuentaCompleted(this, new DetalleCuentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CuentaUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CuentaUsuario(CuentaUsuario cta) {
            object[] results = this.Invoke("CuentaUsuario", new object[] {
                        cta});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CuentaUsuarioAsync(CuentaUsuario cta) {
            this.CuentaUsuarioAsync(cta, null);
        }
        
        /// <remarks/>
        public void CuentaUsuarioAsync(CuentaUsuario cta, object userState) {
            if ((this.CuentaUsuarioOperationCompleted == null)) {
                this.CuentaUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCuentaUsuarioOperationCompleted);
            }
            this.InvokeAsync("CuentaUsuario", new object[] {
                        cta}, this.CuentaUsuarioOperationCompleted, userState);
        }
        
        private void OnCuentaUsuarioOperationCompleted(object arg) {
            if ((this.CuentaUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CuentaUsuarioCompleted(this, new CuentaUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModificarCuentaUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ModificarCuentaUsuario(CuentaUsuario cta) {
            object[] results = this.Invoke("ModificarCuentaUsuario", new object[] {
                        cta});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ModificarCuentaUsuarioAsync(CuentaUsuario cta) {
            this.ModificarCuentaUsuarioAsync(cta, null);
        }
        
        /// <remarks/>
        public void ModificarCuentaUsuarioAsync(CuentaUsuario cta, object userState) {
            if ((this.ModificarCuentaUsuarioOperationCompleted == null)) {
                this.ModificarCuentaUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificarCuentaUsuarioOperationCompleted);
            }
            this.InvokeAsync("ModificarCuentaUsuario", new object[] {
                        cta}, this.ModificarCuentaUsuarioOperationCompleted, userState);
        }
        
        private void OnModificarCuentaUsuarioOperationCompleted(object arg) {
            if ((this.ModificarCuentaUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificarCuentaUsuarioCompleted(this, new ModificarCuentaUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarCuentaUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EliminarCuentaUsuario(int id) {
            object[] results = this.Invoke("EliminarCuentaUsuario", new object[] {
                        id});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EliminarCuentaUsuarioAsync(int id) {
            this.EliminarCuentaUsuarioAsync(id, null);
        }
        
        /// <remarks/>
        public void EliminarCuentaUsuarioAsync(int id, object userState) {
            if ((this.EliminarCuentaUsuarioOperationCompleted == null)) {
                this.EliminarCuentaUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarCuentaUsuarioOperationCompleted);
            }
            this.InvokeAsync("EliminarCuentaUsuario", new object[] {
                        id}, this.EliminarCuentaUsuarioOperationCompleted, userState);
        }
        
        private void OnEliminarCuentaUsuarioOperationCompleted(object arg) {
            if ((this.EliminarCuentaUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarCuentaUsuarioCompleted(this, new EliminarCuentaUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CuentaUsuario {
        
        private int idField;
        
        private string nombreCuentaField;
        
        private string descripcionField;
        
        private string monedaField;
        
        private decimal balanceInicialField;
        
        private decimal balanceActualField;
        
        private string tagsField;
        
        private int usuarioExtraInfoIdField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string NombreCuenta {
            get {
                return this.nombreCuentaField;
            }
            set {
                this.nombreCuentaField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public string Moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
            }
        }
        
        /// <remarks/>
        public decimal BalanceInicial {
            get {
                return this.balanceInicialField;
            }
            set {
                this.balanceInicialField = value;
            }
        }
        
        /// <remarks/>
        public decimal BalanceActual {
            get {
                return this.balanceActualField;
            }
            set {
                this.balanceActualField = value;
            }
        }
        
        /// <remarks/>
        public string Tags {
            get {
                return this.tagsField;
            }
            set {
                this.tagsField = value;
            }
        }
        
        /// <remarks/>
        public int UsuarioExtraInfoId {
            get {
                return this.usuarioExtraInfoIdField;
            }
            set {
                this.usuarioExtraInfoIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetCuentaUSuarioCompletedEventHandler(object sender, GetCuentaUSuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCuentaUSuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCuentaUSuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CuentaUsuario[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CuentaUsuario[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void DetalleCuentaCompletedEventHandler(object sender, DetalleCuentaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DetalleCuentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DetalleCuentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CuentaUsuario Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CuentaUsuario)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CuentaUsuarioCompletedEventHandler(object sender, CuentaUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CuentaUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CuentaUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ModificarCuentaUsuarioCompletedEventHandler(object sender, ModificarCuentaUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ModificarCuentaUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ModificarCuentaUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void EliminarCuentaUsuarioCompletedEventHandler(object sender, EliminarCuentaUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarCuentaUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarCuentaUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591